import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFacebook } from "@fortawesome/free-brands-svg-icons";
import { faGoogle } from "@fortawesome/free-brands-svg-icons";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.shapeBlue}></div>
        <div className={styles.shapeOrange}></div>
        <form className={styles.form}>
          <h3>Login Here</h3>
          <label htmlFor="username">Username</label>
          <input type="text" placeholder="Email or Phone" id="username" />

          <label htmlFor="password">Password</label>
          <input type="password" placeholder="Password" id="password" />

          <button>Log In</button>

          <div className={styles.social}>
            <div className="go">
              <FontAwesomeIcon icon={faGoogle} /> Google
            </div>
            <div className={styles.fb}>
              <FontAwesomeIcon icon={faFacebook} /> Facebook
            </div>
          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        <p>Powered by Luis Valgoi 😋</p>
      </footer>
    </div>
  );
};

export default Home;
